### PR TITLE
Pull Request Description 🚀

### PR DESCRIPTION
**Pull request by Emmanuel10701**
This PR introduces several important updates, including the creation of a custom 404 page 🛠️ to handle "not found" errors and improve user experience. Additionally, Google login integration 🔐 has been added to simplify authentication. The contact form 📩 has been enhanced with better state management and notifications 🔔 for success or failure. Various bug fixes 🐞 and styling improvements 🎨 have also been applied to ensure smooth functionality and responsive design. This update contributes to a more user-friendly, dynamic, and polished app experience! 🎉

### CODE REVIEW

**Comment by Emmanuel10701** [comment]
I hope you will find it Useful
log

**Review by vikas-ukani — APPROVED** [review]
Nice work. :+1:

**Comment by Emmanuel10701** [comment]
is there any  things that you will need I to contribute to make it more moderns Vikash

**Comment by Emmanuel10701** [comment]
Hi Vikas,

I hope this message finds you well. Thank you so much for merging my recent
commits into the main branch of the *Ecommerce-Django-NextJS* project. It’s
been an exciting experience contributing, and I truly value the opportunity
to collaborate on such a meaningful project.

I would love to continue contributing and help with other areas where my
skills could be of use. I’ve deeply specialized in Django, Next.js, React,
and have a foundational understanding of machine learning. If there are any
features, improvements, or areas where I can assist, I would be more than
happy to jump in and help.

Looking forward to hearing your thoughts and continuing to contribute!

Best regards,
Emmanuel

**Pull request merged**
